### ISSUE TITLE
Report missing data

### ISSUE THREAD

**Issue by dholroyd** [russelltg/srt-rs#86] opened 2021-04-02 10:52 UTC
If data is lost on the network, or dropped because it arrived too late, it would be great to have a way to tell where the losses lie within the data actually available.

Is this already possible?   Looking at the API, I suppose it could be signaled via some kind of `Err(io:Error)` response?

If not possible right now, consider expanding the API so an application can know data was lost before it attempts to process the next data following the loss.

**Comment by russelltg** [comment] 2021-04-04 21:44
Duplicate of #70 

This is not currently implemented--there is a plan to however.

**Closed by russelltg** 2021-04-04 21:44 UTC
